// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

type Module = typeof import("../article.js")

type Info = GetInfo<{
  file: "routes/article.tsx",
  module: Module
}>

type Matches = [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:kategoriya-zemli";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:koefficienty-zastrojki";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:smeta-bez-syurprizov";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:stroitelstvo-dlya-nerezidenta";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:oplata-stroitelstva-iz-za-rubezha";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:monolitnyj-karkas";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:kategoriya-zemli";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:koefficienty-zastrojki";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:smeta-bez-syurprizov";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:stroitelstvo-dlya-nerezidenta";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:oplata-stroitelstva-iz-za-rubezha";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:monolitnyj-karkas";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:kategoriya-zemli";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:koefficienty-zastrojki";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:smeta-bez-syurprizov";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:stroitelstvo-dlya-nerezidenta";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:oplata-stroitelstva-iz-za-rubezha";
  module: typeof import("../article.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:monolitnyj-karkas";
  module: typeof import("../article.js");
}];

type Annotations = GetAnnotations<Info & { module: Module, matches: Matches }>;

export namespace Route {
  // links
  export type LinkDescriptors = Annotations["LinkDescriptors"];
  export type LinksFunction = Annotations["LinksFunction"];

  // meta
  export type MetaArgs = Annotations["MetaArgs"];
  export type MetaDescriptors = Annotations["MetaDescriptors"];
  export type MetaFunction = Annotations["MetaFunction"];

  // headers
  export type HeadersArgs = Annotations["HeadersArgs"];
  export type HeadersFunction = Annotations["HeadersFunction"];

  // middleware
  export type MiddlewareFunction = Annotations["MiddlewareFunction"];

  // clientMiddleware
  export type ClientMiddlewareFunction = Annotations["ClientMiddlewareFunction"];

  // loader
  export type LoaderArgs = Annotations["LoaderArgs"];

  // clientLoader
  export type ClientLoaderArgs = Annotations["ClientLoaderArgs"];

  // action
  export type ActionArgs = Annotations["ActionArgs"];

  // clientAction
  export type ClientActionArgs = Annotations["ClientActionArgs"];

  // HydrateFallback
  export type HydrateFallbackProps = Annotations["HydrateFallbackProps"];

  // ServerHydrateFallback
  export type ServerHydrateFallbackProps = Annotations["ServerHydrateFallbackProps"];

  // Component
  export type ComponentProps = Annotations["ComponentProps"];

  // ServerComponent
  export type ServerComponentProps = Annotations["ServerComponentProps"];

  // ErrorBoundary
  export type ErrorBoundaryProps = Annotations["ErrorBoundaryProps"];

  // ServerErrorBoundary
  export type ServerErrorBoundaryProps = Annotations["ServerErrorBoundaryProps"];
}