// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

type Module = typeof import("../landing.js")

type Info = GetInfo<{
  file: "routes/landing.tsx",
  module: Module
}>

type Matches = [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:investoru-v-tbilisi";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:biznesu-sklad-i-ceh";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:dom-pod-otdelku";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:podryad-na-monolit";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:uchastok-na-sklone";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:investoru-v-tbilisi";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:biznesu-sklad-i-ceh";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:dom-pod-otdelku";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:podryad-na-monolit";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:uchastok-na-sklone";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:investoru-v-tbilisi";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:biznesu-sklad-i-ceh";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:dom-pod-otdelku";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:podryad-na-monolit";
  module: typeof import("../landing.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:uchastok-na-sklone";
  module: typeof import("../landing.js");
}];

type Annotations = GetAnnotations<Info & { module: Module, matches: Matches }>;

export namespace Route {
  // links
  export type LinkDescriptors = Annotations["LinkDescriptors"];
  export type LinksFunction = Annotations["LinksFunction"];

  // meta
  export type MetaArgs = Annotations["MetaArgs"];
  export type MetaDescriptors = Annotations["MetaDescriptors"];
  export type MetaFunction = Annotations["MetaFunction"];

  // headers
  export type HeadersArgs = Annotations["HeadersArgs"];
  export type HeadersFunction = Annotations["HeadersFunction"];

  // middleware
  export type MiddlewareFunction = Annotations["MiddlewareFunction"];

  // clientMiddleware
  export type ClientMiddlewareFunction = Annotations["ClientMiddlewareFunction"];

  // loader
  export type LoaderArgs = Annotations["LoaderArgs"];

  // clientLoader
  export type ClientLoaderArgs = Annotations["ClientLoaderArgs"];

  // action
  export type ActionArgs = Annotations["ActionArgs"];

  // clientAction
  export type ClientActionArgs = Annotations["ClientActionArgs"];

  // HydrateFallback
  export type HydrateFallbackProps = Annotations["HydrateFallbackProps"];

  // ServerHydrateFallback
  export type ServerHydrateFallbackProps = Annotations["ServerHydrateFallbackProps"];

  // Component
  export type ComponentProps = Annotations["ComponentProps"];

  // ServerComponent
  export type ServerComponentProps = Annotations["ServerComponentProps"];

  // ErrorBoundary
  export type ErrorBoundaryProps = Annotations["ErrorBoundaryProps"];

  // ServerErrorBoundary
  export type ServerErrorBoundaryProps = Annotations["ServerErrorBoundaryProps"];
}