// Generated by React Router

import type { GetInfo, GetAnnotations } from "react-router/internal";

type Module = typeof import("../object.js")

type Info = GetInfo<{
  file: "routes/object.tsx",
  module: Module
}>

type Matches = [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:obekt-saburtalo";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:obekt-rustavi";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:obekt-tskhneti";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:obekt-vake";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:obekt-gldani";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:obekt-lisi";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:obekt-digomi";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:obekt-marneuli";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ru";
  module: typeof import("../locale.js");
}, {
  id: "ru:obekt-betania";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:obekt-saburtalo";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:obekt-rustavi";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:obekt-tskhneti";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:obekt-vake";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:obekt-gldani";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:obekt-lisi";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:obekt-digomi";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:obekt-marneuli";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-en";
  module: typeof import("../locale.js");
}, {
  id: "en:obekt-betania";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:obekt-saburtalo";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:obekt-rustavi";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:obekt-tskhneti";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:obekt-vake";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:obekt-gldani";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:obekt-lisi";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:obekt-digomi";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:obekt-marneuli";
  module: typeof import("../object.js");
}] | [{
  id: "root";
  module: typeof import("../../root.js");
}, {
  id: "lang-ka";
  module: typeof import("../locale.js");
}, {
  id: "ka:obekt-betania";
  module: typeof import("../object.js");
}];

type Annotations = GetAnnotations<Info & { module: Module, matches: Matches }>;

export namespace Route {
  // links
  export type LinkDescriptors = Annotations["LinkDescriptors"];
  export type LinksFunction = Annotations["LinksFunction"];

  // meta
  export type MetaArgs = Annotations["MetaArgs"];
  export type MetaDescriptors = Annotations["MetaDescriptors"];
  export type MetaFunction = Annotations["MetaFunction"];

  // headers
  export type HeadersArgs = Annotations["HeadersArgs"];
  export type HeadersFunction = Annotations["HeadersFunction"];

  // middleware
  export type MiddlewareFunction = Annotations["MiddlewareFunction"];

  // clientMiddleware
  export type ClientMiddlewareFunction = Annotations["ClientMiddlewareFunction"];

  // loader
  export type LoaderArgs = Annotations["LoaderArgs"];

  // clientLoader
  export type ClientLoaderArgs = Annotations["ClientLoaderArgs"];

  // action
  export type ActionArgs = Annotations["ActionArgs"];

  // clientAction
  export type ClientActionArgs = Annotations["ClientActionArgs"];

  // HydrateFallback
  export type HydrateFallbackProps = Annotations["HydrateFallbackProps"];

  // ServerHydrateFallback
  export type ServerHydrateFallbackProps = Annotations["ServerHydrateFallbackProps"];

  // Component
  export type ComponentProps = Annotations["ComponentProps"];

  // ServerComponent
  export type ServerComponentProps = Annotations["ServerComponentProps"];

  // ErrorBoundary
  export type ErrorBoundaryProps = Annotations["ErrorBoundaryProps"];

  // ServerErrorBoundary
  export type ServerErrorBoundaryProps = Annotations["ServerErrorBoundaryProps"];
}